<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OT8OU31" name="Default test" tests="6" failures="1" timestamp="26 Apr 2018 06:32:48 GMT" time="0.059" errors="0">
  <testcase name="assertEquals" time="0.019" classname="seleniummukesh.Hardassertiondifferent">
    <failure type="java.lang.AssertionError" message="expected [This assertion will fail] but found [assertion]">
      <![CDATA[java.lang.AssertionError: expected [This assertion will fail] but found [assertion]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at seleniummukesh.Hardassertiondifferent.assertEquals(Hardassertiondifferent.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- assertEquals -->
  <testcase name="assertFalse" time="0.002" classname="seleniummukesh.Hardassertiondifferent"/>
  <testcase name="assertNotEquals" time="0.002" classname="seleniummukesh.Hardassertiondifferent"/>
  <testcase name="assertNotNull" time="0.002" classname="seleniummukesh.Hardassertiondifferent"/>
  <testcase name="assertNull" time="0.001" classname="seleniummukesh.Hardassertiondifferent"/>
  <testcase name="assertTrue" time="0.002" classname="seleniummukesh.Hardassertiondifferent"/>
</testsuite> <!-- Default test -->
