package javamukesh;

public class Finally {

	public static void main(String[] args) {
	
		test();
		test2();
	}

	public  static void test(){
		try{
			System.out.println("inside the try block");
			throw new RuntimeException("test");
			
		}catch (Exception e){
			System.out.println("inside the catch block");
		}
	finally
	{
		System.out.println("inside the finally block");
	}
}
	public static void test2(){
		try{
			System.out.println("inside the test2 block");
		}
		finally {
			System.out.println("inside the finally test2 block");
		}
	}
	}
